<b>Solving Transportation problem using NWC method</b>
- Give any dimension of supply and demand values in second kernel this method will give the Basic feasible solution and the cost associated with it :)
- Make sure you give positive values and total supply = total demand

In [9]:
import numpy as np

def optimization_using_northwest_corner(supply,demand,cost_of_solution_row_wise):
    #Making sure no value is below zero
    if is_num_below_zero(supply) or is_num_below_zero(demand) or is_num_below_zero(cost_of_solution_row_wise):
          raise Exception("Please enter number above zero")
    dimension_supply = len(supply)
    dimension_demand = len(demand)
    initial_matrix = np.zeros((dimension_supply+1, dimension_demand+1))
    #Setting the last column as supply and last row as demand
    for i in range(len(supply)):
        initial_matrix[i,-1] = supply[i]
    for j in range(len(demand)):
        initial_matrix[-1,j] = demand[j]
    #Setting the last value of the matrix as the sum of supply/demand
    initial_matrix[-1,-1] = np.sum(initial_matrix[:,-1])
    solution_matrix = initial_matrix.copy()
    #Printing the initial matrix with supply and demand
    print("Initial matrix\n",initial_matrix,"\n")
    
    for i in range(dimension_supply):
        for j in range(dimension_demand):
            #Setting the minimum of supply and demand values in following variable
            minimum_of_supply_demand = np.minimum(initial_matrix[i,dimension_demand],initial_matrix[dimension_supply,j])
            #subracting both supply and demand by the minimum value
            initial_matrix[dimension_supply,j] = initial_matrix[dimension_supply,j] - minimum_of_supply_demand
            initial_matrix[i,dimension_demand] = initial_matrix[i,dimension_demand] - minimum_of_supply_demand
            solution_matrix[i,j] = minimum_of_supply_demand
    print("solution matrix\n",solution_matrix,"\n")
    
    #Reshaping the single array to matrix form
    reshaping_cost_of_solution = cost_of_solution_row_wise.reshape(dimension_supply,dimension_demand)
    #Adding zeros to rows and columns
    rows_with_zeros = np.hstack((reshaping_cost_of_solution, np.zeros((reshaping_cost_of_solution.shape[0], 1), dtype=reshaping_cost_of_solution.dtype)))
    columns_with_zeros = np.vstack((rows_with_zeros, np.zeros((1,rows_with_zeros.shape[1]), dtype=rows_with_zeros.dtype)))
    #printing the original cost function with added zeros and columns
    cost_matrix = np.matrix(columns_with_zeros)
    print("Initial Cost matrix\n",cost_matrix,"\n")
    #Finding cost of the solution and adding all the costs
    cost_of_solution = np.multiply(solution_matrix,cost_matrix)
    total_cost_of_solution = np.sum(cost_of_solution)
    print("Solution with Cost matrix \n",cost_of_solution,"\n")
    print("Total cost of the solution : ",total_cost_of_solution)
    
#Checking if any number is below zero    
def is_num_below_zero(num):
    for i in num:
        if i < 0:
            return True
    return False


<b>Now let's try with few values and verify</b>

In [10]:
supply = [14,16,20]
demand = [11,15,14,10]
cost_of_solution_row_wise = np.array([180,110,130,290,190,250,150,280,240,270,190,120])
optimization_using_northwest_corner(supply,demand,cost_of_solution_row_wise)

Initial matrix
 [[ 0.  0.  0.  0. 14.]
 [ 0.  0.  0.  0. 16.]
 [ 0.  0.  0.  0. 20.]
 [11. 15. 14. 10. 50.]] 

solution matrix
 [[11.  3.  0.  0. 14.]
 [ 0. 12.  4.  0. 16.]
 [ 0.  0. 10. 10. 20.]
 [11. 15. 14. 10. 50.]] 

Initial Cost matrix
 [[180 110 130 290   0]
 [190 250 150 280   0]
 [240 270 190 120   0]
 [  0   0   0   0   0]] 

Solution with Cost matrix 
 [[1980.  330.    0.    0.    0.]
 [   0. 3000.  600.    0.    0.]
 [   0.    0. 1900. 1200.    0.]
 [   0.    0.    0.    0.    0.]] 

Total cost of the solution :  9010.0


In [11]:
supply = [30,20,35,35]
demand = [30,40,50]
cost_of_solution_row_wise = np.array([10,11,6,4,5,9,3,8,7,11,10,9])
optimization_using_northwest_corner(supply,demand,cost_of_solution_row_wise)

Initial matrix
 [[  0.   0.   0.  30.]
 [  0.   0.   0.  20.]
 [  0.   0.   0.  35.]
 [  0.   0.   0.  35.]
 [ 30.  40.  50. 120.]] 

solution matrix
 [[ 30.   0.   0.  30.]
 [  0.  20.   0.  20.]
 [  0.  20.  15.  35.]
 [  0.   0.  35.  35.]
 [ 30.  40.  50. 120.]] 

Initial Cost matrix
 [[10 11  6  0]
 [ 4  5  9  0]
 [ 3  8  7  0]
 [11 10  9  0]
 [ 0  0  0  0]] 

Solution with Cost matrix 
 [[300.   0.   0.   0.]
 [  0. 100.   0.   0.]
 [  0. 160. 105.   0.]
 [  0.   0. 315.   0.]
 [  0.   0.   0.   0.]] 

Total cost of the solution :  980.0


In [12]:
supply = [32,44,34]
demand = [28,45,37]
cost_of_solution_row_wise = np.array([150,213,222,175,204,218,188,198,246])
optimization_using_northwest_corner(supply,demand,cost_of_solution_row_wise)

Initial matrix
 [[  0.   0.   0.  32.]
 [  0.   0.   0.  44.]
 [  0.   0.   0.  34.]
 [ 28.  45.  37. 110.]] 

solution matrix
 [[ 28.   4.   0.  32.]
 [  0.  41.   3.  44.]
 [  0.   0.  34.  34.]
 [ 28.  45.  37. 110.]] 

Initial Cost matrix
 [[150 213 222   0]
 [175 204 218   0]
 [188 198 246   0]
 [  0   0   0   0]] 

Solution with Cost matrix 
 [[4200.  852.    0.    0.]
 [   0. 8364.  654.    0.]
 [   0.    0. 8364.    0.]
 [   0.    0.    0.    0.]] 

Total cost of the solution :  22434.0
